name: 'Convert Mermaid Markdown into an image'
branding:
  icon: 'grid'
  color: 'green'
inputs:
  inFile:
    description: 'the path to the input file to convert'
    required: true
  outFile:
    description: 'where to output the file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-i'
    - ${{ inputs.inFile }}
    - '-o'
    - ${{ inputs.outFile }}

