name: 'Convert Mermaid Markdown into an image'
branding:
  icon: 'grid'
  color: 'green'
inputs:
  inFolder:
    description: 'the path to the input folder with .mmd files to convert'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    ${{ inputs.inFolder }}

