name: 'Compile Mermaid in Markdown'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: 3shape/threeshape.mermaid.diagram.converter@master
      with:
        inFolder: './test-data/'
    
    - uses: actions/upload-artifact@v1
      with:
        name: output
        path: ./test-data
  